# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.2.2.{build}                 # You can use {branch} to, for example

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    # windows ci is so slow, so test it less frequently with another branch
    - release
    - master

  # blacklist
  # except:
  #   - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

# Skipping commits with particular message or from user
# skip_commits:
#   message: /Created.*\.(png|jpg|jpeg|bmp|gif)/       # Regex for matching commit message
#   author: John        # Commit author's username, name, email or regexp maching one of these.

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\gopath\src\github.com\oliveagle\hickwall

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# setting up etc\hosts file
# hosts:
#   queue-server: 127.0.0.1
#   db.server.com: 127.0.0.2

environment:
  GOPATH: c:\gopath

# scripts that run after cloning repository
install:
  # install and use golang 1.4
  # - set Path=c:\tools\go\bin;%Path%
  # - echo %PATH%
  # - choco version
  # - cinst golang -Version 1.4
  # - set GOROOT=c:\tools\go
  # - echo %APPVEYOR_BUILD_FOLDER%
  - SET PATH=%GOPATH%\bin;%PATH%
  - go version
  - go env
  - go get -u github.com/mattn/gom

  - cd %APPVEYOR_BUILD_FOLDER%

  - choco install wget
  - wget "http://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.8.2/threads-posix/seh/x86_64-4.8.2-release-posix-seh-rt_v3-rev4.7z?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fmingw-w64%2Ffiles%2FToolchains%2520targetting%2520Win64%2FPersonal%2520Builds%2Fmingw-builds%2F4.8.2%2Fthreads-posix%2Fseh%2F&ts=1435582105&use_mirror=nchc" -O mingw64.7z
  - 7z.exe x mingw64.7z -oc:\mingw64
  - SET PATH=%GOPATH%\bin;c:\mingw64\bin;%PATH%


  - md _vendor\src\code.google.com\p\winsvc
  - git clone https://github.com/oliveagle/winsvc.git _vendor\src\code.google.com\p\winsvc

  - md _vendor\src\code.google.com\p\snappy-go
  - git clone https://github.com/VividCortex/snappy-go.git _vendor\src\code.google.com\p\snappy-go

  - md _vendor\src\github.com\influxdb\influxdb_088
  - git clone https://github.com/influxdb/influxdb.git _vendor\src\github.com\influxdb\influxdb_088

  - cd %APPVEYOR_BUILD_FOLDER%
  # - cd _vendor\src\github.com\influxdb\influxdb_088
  # - git checkout v0.8.8
  # - cd %APPVEYOR_BUILD_FOLDER%
  - gom install

build_script:
- SET PATH=%GOPATH%\bin;%PATH%
- gom test -v ./...

# to disable automatic tests
test: off

# to disable deployment
deploy: off