port = ":9977"

# Levels: trace, debug, info, warn, error, critical
log_console_level = "debug"
log_colored_console = true

# Format :
log_console_format = "%Time [%LEV] %Msg%n"

log_file_filepath = "/var/log/hickwall/hickwall.log"
log_file_level = "debug"
log_file_format = "%Date %Time [%Level] %RelFile %Msg%n"
#log_file_format = "%Date(2006 Jan 02/3:04:05.000000000 PM MST) [%Level] %RelFile %Msg%n"

# calculated in Mb
log_file_maxsize = 100

#
log_file_maxrolls = 5