# ---------- log configurations -------------------------------------------
# Levels: trace, debug, info, warn, error, critical
log_level: "debug"

# calculated in Mb
# alway >=1
log_file_maxsize: 100

# alway >=1
log_file_maxrolls: 5

#TODO: memory_limit_in_mb
# when use 'memory' transport cache backend, we have to set a hard limit to prevent memory leak
# once this limit reached, the client will restart automatically
memory_limit_in_mb: 500


# above configurations always needed

enable_remote_config: false

# use this to retrive remote configuration
# Viper will read a config string (as JSON, TOML, or YAML) retrieved from a path 
# in a Key/Value store such as Etcd or Consul. These values take precedence over 
# default values, but are overriden by configuration values retrieved from disk

# the last good configuration from remote will be cached locally. 

# current only support etcd
remote_config_protocal: "etcd"
remote_config_url: "http://127.0.0.1:4001"
remote_config_path: "/config/host/DST54869.json"
