FROM phusion/baseimage:0.9.16
MAINTAINER oliveagle@gmail.com

COPY ./source.list /etc/apt/sources.list
 




# --------------------- #
# build with all assets #
# --------------------- #

# ----------- #
#   Cleanup   #
# ----------- #

# RUN apt-get autoremove -y wget curl && \
#  apt-get -y clean && \
#  rm -rf /var/lib/apt/lists/*
